subreddit:
  original:
  new:

user:
  limit: 30
  username:
  password:
  client_id:
  client_secret:
  user_agent: script:reddit anti-censorship bot:v0.1.0:created by /u/rpdorm
  debug: False
  sleep: 300